version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    environment:
      - MINIO_ACCESS_KEY=ahmad
      - MINIO_SECRET_KEY=12345678
    ports:
      - "5000:5000"
    depends_on:
      - minio
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=ahmad
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  minio-data: 
